name: TestPlugin
version: '1.3'
main: fr.minepitech.testPlugin.TestPlugin
api-version: '1.21'
authors: [ clement ]
description: BOSS LADY


commands:
  clemFly:
    description: Permet de voler
    usage: /clemFly
  clemBaguette:
    description: Donne une baguette qui lance des boules de feu
    usage: /clemBaguette

  clemTimer:
    description: Permet de mettre un timer
    usage: /clemTimer <time in seconds>


